config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :subjects do
    resources :attends do
      collection do
        delete 'destroy_all'
      end
    end
  end

  root to:"attends#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attend.rb
class Attend < ApplicationRecord
  belongs_to :subject
  with_options presence: true do
    validates :latitude
    validates :longitude
    validates :student_number
    validates :name
    validates :ip, uniqueness: true
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :timetable
  belongs_to :week

  has_many :attends
  belongs_to :user

  with_options numericality: { other_than: 1, message: '時間割、曜日を選択してください' } do
    validates :timetable_id
    validates :week_id
  end
end

app/models/timetable.rb
class Timetable < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '1時限目' },
    { id: 3, name: '2時限目' },
    { id: 4, name: '3時限目' },
    { id: 5, name: '4時限目' },
    { id: 6, name: '5時限目' },
    { id: 7, name: '6時限目' }
  ]
  include ActiveHash::Associations
  has_many :subjects
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :attends
end

app/models/week.rb
class Week < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '月曜日' },
    { id: 3, name: '火曜日' },
    { id: 4, name: '水曜日' },
    { id: 5, name: '木曜日' },
    { id: 6, name: '金曜日' },
    { id: 7, name: '土曜日' }
  ]
  include ActiveHash::Associations
  has_many :subjects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attends_controller.rb
class AttendsController < ApplicationController
  require 'csv'

  def index
    @subject = Subject.where(user_id: current_user.id).order('week_id ASC') if user_signed_in?
  end

  def new
    @subject = Subject.find(params[:subject_id])
    @attend = Attend.new
    @attends = Attend.all
    respond_to do |format|
      format.html
      format.csv do |_csv|
        send_posts_csv(@attends)
      end
    end
  end

  def create
    @subject = Subject.find(params[:subject_id])
    @attend = Attend.new(params_attend)
    @attends = Attend.all
    unless @attend.save
      render :new
    end
  end

  def destroy_all
    Attend.destroy_all
    redirect_to root_path
  end

  private

  def params_attend
    @ip = request.remote_ip
    params.require(:attend).permit(:name, :student_number, :latitude, :longitude).merge(ip: @ip,
                                                                                        subject_id: params[:subject_id])
  end

  def send_posts_csv(attends)
    csv_data = CSV.generate do |csv|
      column_names = %w[名前 学籍番号 出席時間 緯度 経度]
      csv << column_names
      attends.each do |attend|
        column_values = [
          attend.name,
          attend.student_number,
          attend.created_at,
          attend.latitude,
          attend.longitude
        ]
        csv << column_values
      end
    end
    send_data(csv_data, filename: '出席一覧.csv')
  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(params_subject)
    if @subject.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    @subject = Subject.find(params[:id])
    if @subject.update(params_subject)
      redirect_to root_path(current_user.id)
    else
      render :edit
    end
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    redirect_to root_path(current_user.id)
  end

  private

  def params_subject
    params.required(:subject).permit(:subject, :timetable_id, :week_id).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attends_helper.rb
module AttendsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/attends/_error_message.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
      <h1 class="alert"><注意>アクセスが不正です</h1>
  </div>
<% end %>

app/views/attends/create.html.erb
<%= render "shared/header" %>
<div class="main">
  <h1 class="message">出席できました</h1>
  <u><%= link_to "戻る",new_subject_attend_path ,class:"exit"%></u>
</div>
<%= render "shared/footer" %>

app/views/attends/index.html.erb
<%= render "shared/header" %>
<div class="main">
  <% if user_signed_in? %>
    <%if @subject.exists?%>
      <% @subject.each do |subject| %>
        <div class="subject-contents">
          <div class="subject-content">
            <%= link_to subject.subject, "#", class:"subject-title"%>
            <p class="sub-subject-title">(<%= subject.week.name%><%= subject.timetable.name%>)</p>
          </div>
          <div class="subject-attend">
            <%=link_to "出席をとる", new_subject_attend_path(subject.id), class:"subject-attend-btn"%>
          </div>
          <div class="subject-contents-edit">
            <%= link_to "編集する", edit_subject_path(subject.id), class:"subject-content-edit left"%>
            <%= link_to "削除する", subject_path(subject.id), class:"subject-content-edit rigth", method: :delete%>
          </div>
        </div>
      <% end %>
    <%else%>
      <p class="message">教科を作成しましょう</p>
    <%end%>
  <%else%>
  <p class="message">ログインしてください</p>
  <%end%>
</div>
<%= render "shared/footer" %>

app/views/attends/new.html.erb
<%= render "shared/header" %>
<div class="main">
  <%=form_with model: [@subject, @attend],class:"form-content", local: true do |f|%>
  <%= render 'error_message', model: f.object %>
    <h1 class="title">出席確認</h1>
    <div>
      <p class="sub_title">名前</p>
      <%= f.text_field :name, class:"form", id:"name" %>
    </div>
    <div>
      <p class="sub_title">学籍番号</p>
      <%= f.text_field :student_number, class:"form", id:"student_number" %>
    </div>
    <div class="hidden">
      <p class="sub_title">緯度</p>
      <%= f.text_field :latitude, class:"form", id:"latitude" %>
    </div>
    <div class="hidden">
      <p class="sub_title">経度</p>
      <%= f.text_field :longitude,class:"form", id:"longitude" %>
    </div>
    <div >
      <%= f.submit "出席する" ,class:"btn", id:"btn"%>
    </div>
  <%end%>
  <% if user_signed_in? %>
  <div class="user-contents">
    <div class="attended">
      <div class="name">
      名前
      </div>
      <div class="number">
      学籍番号
      </div>
      <div class="time hidden">
      入力時間
      </div>
      <div class="latitude hidden">
      緯度
      </div>
      <div class="longitude hidden">
      経度
      </div>
    </div>
    <%if @attends.exists?%>
    <% @attends.each do |attend|%>
    <div class="attended">
      <div class="name">
      <%= attend.name%>
      </div>
      <div class="number">
      <%= attend.student_number%>
      </div>
      <div class="time hidden">
      <%= attend.created_at.to_s(:datetime_jp)%>
      </div>
      <div class="latitude hidden">
      <%= attend.latitude%>
      </div>
      <div class="longitude hidden">
      <%= attend.longitude%>
      </div>
    </div>
    <%end%>
    <%end%>
    <div class="create-date">
      <%= link_to "csvで出力する",new_subject_attend_path(format: :csv), class:"create-date-message"  %>
      <%= link_to "保存できたので削除",destroy_all_subject_attends_path, method: :delete , class:"delete-btn"%>
    </div>
  </div>
  <%end%>
</div>
<%= render "shared/footer" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AttendApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
<a href="#" class="inquiry">--footer--</a>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="header-left-contents">
    <div class="title-contents">
      <%= link_to "出席管理", root_path, class:"app-title"%>
    </div>
  </div>
  <div class="header-right-contents">
  <% if user_signed_in? %>
    <div class="right-content">
    <%=link_to "教科を作成する", new_subject_path, class:"user-devise right"%>
    </div>
    <div class="left-contents">
    <%= link_to "ログアウトする", destroy_user_session_path, class:"user-devise right", method: :delete%>
    </div>
  <%else%>
    <div class="right-content">
    <%= link_to "ログインする", new_user_session_path, class:"user-devise right"%>
    </div>
    <div class="left-contents">
    <%= link_to "新規登録する", new_user_registration_path, class:"user-devise left"%>
    </div>
  <%end%>
  </div>
</div>

app/views/subjects/edit.html.erb
<%= render "shared/header" %>
<div class="main">
  <%=form_with model: @subject, class:"form-content-registration", local: true do |f|%>
    <div >
      <p class="sub_title-registration">教科名</p>
      <%= f.text_field :subject, class:"form-registration"%>
    </div>
    <div>
      <p class="sub_title-registration">開始時限</p>
      <%= f.collection_select(:timetable_id, Timetable.all, :id, :name, {}, {class:"form-registration"}) %>
    </div>
    <div>
      <p class="sub_title-registration">曜日</p>
      <%= f.collection_select(:week_id, Week.all, :id, :name, {}, {class:"form-registration"}) %>
    </div>
    <div >
      <%= f.submit "登録する" ,class:"btn"%>
    </div>
  <%end%>
</div>
<%= render "shared/footer" %>

app/views/subjects/new.html.erb
<%= render "shared/header" %>
<div class="main">
  <%=form_with model: @subject, class:"form-content-registration", local: true do |f|%>
    <div >
      <p class="sub_title-registration">教科名</p>
      <%= f.text_field :subject, class:"form-registration"%>
    </div>
    <div>
      <p class="sub_title-registration">開始時限</p>
      <%= f.collection_select(:timetable_id, Timetable.all, :id, :name, {}, {class:"form-registration"}) %>
    </div>
    <div>
      <p class="sub_title-registration">曜日</p>
      <%= f.collection_select(:week_id, Week.all, :id, :name, {}, {class:"form-registration"}) %>
    </div>
    <div >
      <%= f.submit "登録する" ,class:"btn"%>
    </div>
  <%end%>
</div>
<%= render "shared/footer" %>